# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 07:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_auto_20191124_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('photo', models.ImageField(default='No Image', upload_to='profile_pics')),
                ('bio', tinymce.models.HTMLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 11, 24, 7, 17, 42, 352020, tzinfo=utc))),
            ],
        ),
    ]
