# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_auto_20191124_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 9, 13, 20, 902473, tzinfo=utc)),
        ),
    ]
