# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_auto_20191124_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 12, 42, 45, 172132, tzinfo=utc)),
        ),
    ]
