# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0008_auto_20191125_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 11, 33, 11, 723979, tzinfo=utc)),
        ),
    ]
